config/routes.rb
Cart::Application.routes.draw do
  resources :users
  resources :categories
  resources :products
  resources :sessions,      only: [:new, :create, :destroy]
  
  resource :pages
  root to: 'pages#home'
  match '/search/', to: 'pages#search', via: :GET
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :get
  match '/cart/add',to: 'cart#add', via: :post
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-header" style="width:100%;z-index:1;">
<h1>Development mode</h1>  
<ul class="nav-top">
      <li>		
          <div class="shop_name header">
                  <h2>
                          <%= link_to 'Warteg Online',root_path %>
                  </h2>		
          </div>
      </li>
      <li>
          <div>
            <%= form_tag("/search", method: "get",:class=>"form-inline", :role=>"form") do %>
               <div class="form-group">
                 
                    <input type="text" name="name" value="cari"  placeholder="Cari" style="height:33px;border-radius:0px;"/>
                 
                </div>
                <div class="form-group">
                  
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span>Cari</button>
                  
                </div>
            <% end %>
          </div>
      </li>
      <li style="float:right;">
          <ul class="nav navbar-nav" id="user-info" >

           <% if signed_in? %>     
          <li>
            
            <%= link_to current_user.username,user %>
            
          </li>
          
          <% else %>
          <li>
            <%= link_to "Login",signin_path %>
          </li>
          <li>
            <%=link_to "Register",signup_path%>
          </li>
          
            <% end %>
          </ul>

      </li>
  </ul>
			</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render 'layouts/header'%>
<%= yield %>
<%= yield :script %>
</body>
</html>